import { arrayBuffer } from "stream/consumers";

export const ganttOptions = {
    removeYAxis: {
        type: "boolean",
        label: "Remove Y Axis",
        display: "checkbox",
        default: false,
        section: "Axes",
    },
    xAxisLineColor: {
        type: "string",
        label: "X Axis Line Color",
        display: "color",
        default: "lightgray",
        section: "Axes",
    },
    xAxisLabelColor: {
        type: "string",
        label: "X Axis Label Color",
        display: "color",
        default: "#2C2D33",
        section: "Axes",
    },
    xAxisLabelSize: {
        type: "string",
        label: "X Axis Label Size",
        display: "text",
        default: "12",
        section: "Axes",
    },
    xAxisTickCount: {
        type: "number",
        label: "X Axis Tick Count",
        display: "range",
        min: 1,
        max: 20,
        step: 1,
        default: 10,
        section: "Axes",
    },
    xAxisFontFamily: {
        type: "string",
        label: "X Axis Font Family",
        display: "text",
        default: '"Google Sans", "Noto Sans", "Noto Sans JP", "Noto Sans CJK KR", "Noto Sans Arabic UI", "Noto Sans Devanagari UI", "Noto Sans Hebrew", "Noto Sans Thai UI", Helvetica, Arial, sans-serif',
        section: "Axes",
    },
    yAxisLabelColor: {
        type: "string",
        label: "Y Axis Label Color",
        display: "color",
        default: "lightgray",
        section: "Axes",
    },
    yAxisLabelSize: {
        type: "string",
        label: "Y Axis Label Size",
        display: "text",
        default: "12",
        section: "Axes",
    },
    yAxisFontFamily: {
        type: "string",
        label: "Y Axis Font Family",
        display: "text",
        default: '"Google Sans", "Noto Sans", "Noto Sans JP", "Noto Sans CJK KR", "Noto Sans Arabic UI", "Noto Sans Devanagari UI", "Noto Sans Hebrew", "Noto Sans Thai UI", Helvetica, Arial, sans-serif',
        section: "Axes",
    },
    rowPaddingPercentage: {
        type: "number",
        label: "Row Padding Percentage",
        display: "range",
        min: 0,
        max: 100,
        step: 1,
        default: 10,
        section: "Style",
    },
    titleColumn: {
        type: "string",
        label: "Title Column",
        display: "select",
        values: [],
        section: "Style",
    },
    chartTitle: {
        type: "string",
        label: "Chart Title",
        display: "text",
        section: "Style",
    },
    titleSize: {
        type: "string",
        label: "Title Size",
        display: "text",
        section: "Style",
        default: "20",
    },
    titleFontFamily: {
        type: "string",
        label: "Title Font Family",
        display: "text",
        default: '"Google Sans", "Noto Sans", "Noto Sans JP", "Noto Sans CJK KR", "Noto Sans Arabic UI", "Noto Sans Devanagari UI", "Noto Sans Hebrew", "Noto Sans Thai UI", Helvetica, Arial, sans-serif',
        section: "Style",
    },
    titleWeight: {
        type: "string",
        label: "Title Weight",
        display: "text",
        default: "400",
        section: "Style",
    },
    titleColor: {
        type: "string",
        label: "Title Color",
        display: "color",
        default: "#2C2D33",
        section: "Style",
    },
    alternateRowColor: {
        type: "array",
        label: "Alternate Row Color",
        display: "color",
        section: "Style",
    },
    yAxisCategories: {
        type: "array",
        label: "Y-Axis Categories",
        display: "text",
        section: "Axes",
    },
    refBand1Name: {
        type: "string",
        label: "Reference Band 1 Name",
        display: "text",
        default: "Reference Band 1",
        section: "Style",
    },
    refBand2Name: {
        type: "string",
        label: "Reference Band 2 Name",
        display: "text",
        default: "Reference Band 2",
        section: "Style",
    },
    refBand1Color: {
        type: "string",
        label: "Reference Band 1 Color",
        display: "color",
        section: "Style",
        default: "rgba(68, 170, 213, 0.1)"
    },
    refBand2Color: {
        type: "string",
        label: "Reference Band 2 Color",
        display: "color",
        section: "Style",
        default: "rgba(68, 170, 213, 0.1)"
    },
    nameDim: {
        type: "string",
        label: "Name Dimension",
        display: "select",
        values: [],
        section: "Data",
    },
    startDim: {
        type: "string",
        label: "Start Dimension",
        display: "select",
        values: [],
        section: "Data",
    },
    endDim: {
        type: "string",
        label: "End Dimension",
        display: "select",
        values: [],
        section: "Data",
    },
    ref1BandStart: {
        type: "string",
        label: "Reference Band 1 Start",
        display: "select",
        values: [],
        section: "Data",
    },
    ref1BandEnd: {
        type: "string",
        label: "Reference Band 1 End",
        display: "select",
        values: [],
        section: "Data",
    },
    ref2BandStart: {
        type: "string",
        label: "Reference Band 2 Start",
        display: "select",
        values: [],
        section: "Data",
    },
    ref2BandEnd: {
        type: "string",
        label: "Reference Band 2 End",
        display: "select",
        values: [],
        section: "Data",
    },
    colorCategory: {
        type: "string",
        label: "Color By Category",
        display: "select",
        values: [],
        section: "Data",
    },
    legendFontSize: {
        type: "string",
        label: "Legend Font Size",
        display: "text",
        section: "Style",
        default: "12",
    },
}